FROM n8nio/n8n:2.36.8

EXPOSE 5678
ENV N8N_LISTEN_ADDRESS=0.0.0.0
# Render free tier = 512 MB total; task runners + heap must stay under that
ENV NODE_OPTIONS=--max-old-space-size=384
ENV N8N_RUNNERS_ENABLED=false
ENV N8N_METRICS=false
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_PERSONALIZATION_ENABLED=false
ENV EXECUTIONS_DATA_PRUNE=true
ENV EXECUTIONS_DATA_MAX_AGE=168
ENV EXECUTIONS_DATA_PRUNE_MAX_COUNT=100
