FROM n8nio/n8n:1.83.2

EXPOSE 5678
ENV N8N_LISTEN_ADDRESS=0.0.0.0
ENV NODE_OPTIONS=--max-old-space-size=460
ENV N8N_METRICS=false
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_PERSONALIZATION_ENABLED=false
ENV EXECUTIONS_DATA_PRUNE=true
ENV EXECUTIONS_DATA_MAX_AGE=168
ENV EXECUTIONS_DATA_PRUNE_MAX_COUNT=100
